# Generated by Django 3.1.7 on 2021-04-13 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20210413_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='ended_at',
        ),
    ]
